<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Uvc.Server</RootNamespace>
    <AssemblyName>Uvc.Server</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../uvc-core/uvc-core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
